### PR TITLE
Use aeson-compat to support aeson >= 2.0

### PR DESCRIPTION
**Pull request by rvl**
This PR lets my favourite file watching tool build with `aeson-2.0.3.0`.

I have built it with ghc-9.0.2 using both `cabal configure --constraint "aeson>=2.0"` and `cabal configure --constraint "aeson<2.0"`.

Thanks!

### CODE REVIEW

**Review by schell — APPROVED** [review]
LGTM, thank you! 🙇

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision to prohibit building `steeloverseer-2.1.0.0` against `aeson-2.0` (https://hackage.haskell.org/package/steeloverseer-2.1.0.0/revisions/) and also revised older releases, eliminating unbuildable configurations.

**Comment by schell** [comment]
Thank you @Bodigrim ! 

@rvl - I'm actually not writing Haskell all that much these days - would either of you like to become a maintainer? I would give you the keys to both this repo and steeloverseer at hackage.

**Comment by Bodigrim** [comment]
@rvl it would be awesome if you pick this up.

**Pull request merged**
