### PR TITLE
Cabal file and GitHub Action

### PR DESCRIPTION
**Pull request by peterbecich**
I expect this will fix the version bound of `aeson` on Hackage: https://github.com/schell/steeloverseer/issues/46

A GitHub Action is generated for Cabal with https://github.com/haskell-CI/haskell-ci

`cabal test` succeeds with GHC 9.2.2

This PR includes https://github.com/schell/steeloverseer/pull/47

### CODE REVIEW

**Review by schell — APPROVED** [review]
LGTM

**Comment by schell** [comment]
Thank you for all the extra CI work!

**Comment by schell** [comment]
Are you interested in taking over ownership of this package? I don't have time, no am I writing Haskell professionally at the moment.

**Comment by peterbecich** [comment]
Thanks @schell . Yes, I would be happy to take over ownership of the package

**Comment by schell** [comment]
@peterbecich I've added you as a collaborator on this repo. If you could give me your hackage username I'll add you to the maintainer's list :)

**Comment by peterbecich** [comment]
@schell great. Yes, please do that, my Hackage username is peterbecich . Thanks

**Comment by schell** [comment]
Done! Thank you! 🙇

**Pull request merged**
